
name: Build and Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Google Cloud
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          
      - name: Log in to Google Container Registry
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/medli:latest

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy medli \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/medli:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
